spring.application.name=drillapi
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash
server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=300MB
