spring.application.name=drillapi
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash
server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=300MB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
